comment more

diff --git a/.github/workflows/coverage.yml b/.github/workflows/coverage.yml
--- a/.github/workflows/coverage.yml
+++ b/.github/workflows/coverage.yml
@@ -107,18 +107,18 @@ jobs:
           #   fi
           # done
 
-          echo "Trying to merge .profraw files."
-          find target/llvm-cov-target -name '*.profraw' -print0 | xargs -0 $LLVM_PROFDATA merge \
-            --failure-mode=warn \
-            --sparse \
-            --output target/nextest.profdata
+          # echo "Trying to merge .profraw files."
+          # find target/llvm-cov-target -name '*.profraw' -print0 | xargs -0 $LLVM_PROFDATA merge \
+          #   --failure-mode=warn \
+          #   --sparse \
+          #   --output target/nextest.profdata
 
-          if [ -s "target/nextest.profdata" ]; then
-            echo "Successfully collected nextest coverage data."
-          else
-            echo "🚨 Error 🚨: Collecting nexttest coverage failed."
-            exit 1
-          fi
+          # if [ -s "target/nextest.profdata" ]; then
+          #   echo "Successfully collected nextest coverage data."
+          # else
+          #   echo "🚨 Error 🚨: Collecting nexttest coverage failed."
+          #   exit 1
+          # fi
 
           ./run_localnet.sh stop ./iota
 
