feat(scripts): add cargo sort script

diff --git a/.github/workflows/lints.yml b/.github/workflows/lints.yml
--- a/.github/workflows/lints.yml
+++ b/.github/workflows/lints.yml
@@ -42,6 +42,26 @@ jobs:
 
       - run: make is-dirty
 
+  cargo-sort:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
+
+      - name: Check Cargo.toml format and sorting and consolidate dependencies
+        run: |
+          pushd scripts/cargo_sort
+          ./run_consolidate.sh --skip-dprint
+          popd
+
+      - name: Check for Cargo.toml diffs after formatting
+        run: |
+          if git status --porcelain | grep -q "Cargo.toml"; then
+            echo "Cargo.toml files not formatted and/or sorted properly, or dependencies not consolidated! Please run the 'scripts/cargo_sort/run_consolidate.sh' script."
+            git diff  # Show the actual diffs
+            exit 1    # Fail the workflow
+          fi
+
   cargo-deny:
     if: (!github.event.pull_request.draft || contains(github.event.pull_request.body, '[run-ci]'))
     runs-on: ubuntu-latest
